dist: xenial
os: linux
language: go

notifications:
  email:
    on_success: change

jobs:
  include:
    - stage: "Unit Test"
      go: "1.13.6"
      before_install:
        - go get -u -v golang.org/x/lint/golint
        - go get -v ./...
      script:
        - go test -v ./...
        - golint -set_exit_status ./...