dist: xenial
os: linux
language: go

notifications:
  email:
    on_success: change

jobs:
  include:
    - stage: "Test"
      go: "1.13.6"
      env:
        - EXTERNAL_WEAVIATE_RUNNING="true"
      before_install:
        - go get -u -v golang.org/x/lint/golint
        - go get -v ./...
      script:
        - docker-compose -f test/docker-compose.yaml up -d
        - echo "Unit tests"
        - go test -v ./weaviateclient/...
        - echo "Integration tests"
        - ( for pkg in $(go list ./... | grep 'weaviate-go-client/test'); do if ! go test -v -count 1 -race "$pkg"; then echo "Test for $pkg failed" >&2; false; exit; fi done)
        - echo "Linting"
        - golint -set_exit_status ./...