name: Create Release
on:
  push:
    # run only on tags
    tags:
      - '**'

jobs:
  gh-release:
    name: Create a GitHub Release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
