name: Tests

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - LICENSE
      - README.md
      - CONTRIBUTE.md
      - CODE_OF_CONDUCT.md
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        auth_integration: [ "auth_enabled", "auth_disabled" ]
    env:
      EXTERNAL_WEAVIATE_RUNNING: false
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
      WCS_DUMMY_CI_PW: ${{ secrets.WCS_DUMMY_CI_PW }}
      OKTA_DUMMY_CI_PW: ${{ secrets.OKTA_DUMMY_CI_PW }}
      INTEGRATION_TESTS_AUTH: ${{ matrix.auth_integration }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Start Weaviate
        run: ./test/start_containers.sh
      - name: Run tests
        run: |
          go test -v ./weaviate/...
          ( for pkg in $(go list ./... | grep 'weaviate-go-client/v4/test'); do if ! go test -v -count 1 -race "$pkg"; then echo "Test for $pkg failed" >&2; false; exit; fi; done)
      - name: Stop Weaviate
        run: ./test/stop_containers.sh
